# -*- coding: utf-8 -*-
"""Myroshnychenko_Victoria_FinalProject2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBMhmeybarRKcMjjQvmRdtEhy8lSzEIx

Використай цей шаблон в роботі з датасетом. Ти можеш додавати комірки за потреби, але не змінюй структуру і послідовність питань. Обмежся функціями з наведених бібліотек.
"""

import requests
import zipfile
import io
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""1. Завантаження датасету"""

url = "https://survey.stackoverflow.co/datasets/stack-overflow-developer-survey-2025.zip"
response = requests.get(url)

csv_filename = 'survey_results_public.csv'
with zipfile.ZipFile(io.BytesIO(response.content)) as z:
    with z.open(csv_filename) as f:
        df = pd.read_csv(f)

df.head()

#Перевірка типи стовпців.
df.info()

##Перевірка статистики.
df.describe()

"""Завдання 1. Підрахунок загальної кількості респондентів"""

resp_count = df['ResponseId'].nunique()
print(f"Загальна кількість респондентів {resp_count}")

"""Завдання 2. Аналіз повноти відповідей респондентів"""

#load schema
csv_filename = 'survey_results_schema.csv'
with zipfile.ZipFile(io.BytesIO(response.content)) as z:
    with z.open(csv_filename) as f:
       df_schema = pd.read_csv(f)

#df_schema.head()

#make correction because for question "How many years of professional work experience" ... "If your answer is '0', please leave blank.
#DO WE NEED THIS CORRECTION???
#df.fillna({"WorkExp": 0}, inplace=True)

#filter out only  columns that represent questions(intersect set)
qname = df_schema["qname"].unique()
questions = df.columns.isin(qname)
questions = df.columns[df.columns.isin(df_schema["qname"])]
question_cols = df[questions]

#go throw  question_cols , analyze with function notna() if value present(True) or not(False), => result is dataframe
#then go throw all derived dataframe row-wize(axis=1) check if All values are True =>result is series with True(1) False(0)
# sum() shows how many "True" present in series so that we can evaluate how many rows in question_cols totaly filled out (answered)
question_all_answered = question_cols.notna().all(axis=1).sum()
print(question_all_answered)
#alternative way
question_all_answered = question_cols.dropna().shape[0]
print(question_all_answered)

"""Завдання 3. Статистичний аналіз досвіду респондентів

DO WE NEED THIS CORRECTION???
make correction because for question "How many years of professional work experience" ... "If your answer is '0', please leave blank.

"""

#without correction
print("Міри центральноі тенденціі")
central_metrics = pd.DataFrame({
    "Mean": pd.Series(dtype="float"),
    "Median": pd.Series(dtype="float"),
    "Mode": pd.Series(dtype="int")
})
central_metrics.loc["WorkExp"] = [round(df['WorkExp'].mean()), df['WorkExp'].median(), df['WorkExp'].mode()[0]]
central_metrics.reset_index(inplace=True)
central_metrics

print("Міри центральноі тенденціі з корекцією пропусків WorkExp на 0")
# коррекция пропусков N\A
#for question "How many years of professional work experience" ... "If your answer is '0', please leave blank.
df_WorkExp_corrected = df[["WorkExp"]]
df_WorkExp_corrected = df_WorkExp_corrected.fillna({"WorkExp": 0})
central_metrics = pd.DataFrame({
    "Mean": pd.Series(dtype="float"),
    "Median": pd.Series(dtype="float"),
    "Mode": pd.Series(dtype="int")
})
central_metrics.loc["WorkExp"] = [round(df_WorkExp_corrected['WorkExp'].mean()), df_WorkExp_corrected['WorkExp'].median(), df_WorkExp_corrected['WorkExp'].mode()[0]]
#central_metrics.reset_index(inplace=True)
central_metrics

"""Завдання 4. Аналіз віддаленої роботи"""

df[df["RemoteWork"]=='Remote'].shape[0]

"""Завдання 5. Визначення популярності Python"""

pythonists_count=df["LanguageHaveWorkedWith"].fillna(False).str.contains("python", case=False).sum()
resp_count = df['ResponseId'].nunique()
print(f"Відсоток респондентів,в що програмують на Python {round(pythonists_count*100/resp_count)} %")

"""Завдання 6. Аналіз шляхів навчання програмуванню"""

online_count=df["LearnCode"].dropna().str.contains("Online Courses", case=False).sum()
print(f"Кількість респондентів, в що обрали онлайн курси {round(online_count)}")

"""Завдання 7. Географічний аналіз компенсації Python-розробників"""

condition = df["LanguageHaveWorkedWith"].str.contains("python", case=False)

df.filter(items=["Country","ConvertedCompYearly","LanguageHaveWorkedWith"])\
.where(condition)\
.dropna()\
.groupby("Country")\
.agg(
        Mean=("ConvertedCompYearly", "mean"),
        Median=("ConvertedCompYearly", "median")
    )\
.round(2)

"""Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів"""

df.filter(items=["ResponseId","EdLevel","ConvertedCompYearly"]).sort_values(by="ConvertedCompYearly",ascending=False).head(5)

"""*Завдання 9. Аналіз популярності Python по віковим категоріям"""



df.filter(items=["ResponseId","Age","LanguageHaveWorkedWith"])\
.dropna()\
.assign(is_python=lambda x: x["LanguageHaveWorkedWith"].str.contains("python", case=False))\
.groupby("Age").agg(
        python=("is_python", "sum"),
        total=("ResponseId", "count")
    )\
.assign(Python_percentage=lambda x: round(x["python"] / x["total"] * 100, 2))\
.filter(items=["Age","Python_percentage"])

df["ConvertedCompYearly"].quantile(0.75)

"""*Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників"""

q75 = df["ConvertedCompYearly"].quantile(0.75)
print(f" 75 перцентил за компенсацією {q75}")
df.filter(items=["ResponseId","RemoteWork","ConvertedCompYearly","Industry"])[(df["RemoteWork"] == "Remote") & (df["ConvertedCompYearly"] >= q75)]\
.dropna()\
.groupby("Industry")\
.agg(
        Freq=("ResponseId", "count")
    ).round()\
    .sort_values(by="Freq",ascending=False)